name: web_app_config
description: Tools for configuring web apps with environment variables and YAML
version: 1.0.0
homepage: https://github.com/johnpryan/web_app_config
author: John Ryan <john.p.ryan4@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: ^0.11.3
  dart2_constant: ^1.0.0
  yaml: ^2.1.13

dev_dependencies:
  test: ^0.12.0
