name: web_app_config
description: Tools for configuring web apps with environment variables and YAML
version: 1.0.0
#homepage: https://www.example.com
#author: john <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: any
  dart2_constant: any
  yaml: any

dev_dependencies:
  test: ^0.12.0
